---

### Generic smell configuration

detectors:
  # You can disable smells completely
  IrresponsibleModule:
    enabled: false

  # A lot of smells allow fine tuning their configuration. You can look up all available options
  # in the corresponding smell documentation in /docs. In most cases you probably can just go
  # with the defaults as documented in defaults.reek.yml.
  DataClump:
    max_copies: 3
    min_clump_size: 3
  UncommunicativeVariableName:
    accept:
      - t
  TooManyStatements:
    enabled: false

  UncommunicativeModuleName:
    enabled: true
    exclude: []
    reject:
      - "/^.$/"
      - "/[0-9]$/"
    accept:
      - Inline::C
      - "/V[0-9]/"

### Directory specific configuration

# You can configure smells on a per-directory base.
# E.g. the classic Rails case: controllers smell of NestedIterators (see /docs/Nested-Iterators.md) and
# helpers smell of UtilityFunction (see docs/Utility-Function.md)
#
# Note that we only allow configuration on a directory level, not a file level,
# so all paths have to point to directories.
# A Dir.glob pattern can be used.
directories:
  "app/controllers":
    NestedIterators:
      enabled: false
  "app/helpers**":
    UtilityFunction:
      enabled: false
  "lib/**/test/**":
    UtilityFunction:
      enabled: false
  "db/migrate":
    FeatureEnvy:
      enabled: false
